### ISSUE TITLE
User gets stuck on "Loading terrain", NPE stacktrace cites WSVD

### ISSUE THREAD

**Issue by triphora** [BasiqueEvangelist/worldspecificviewdistance-fabric#1]
```
21.05 17:10:12 [Server] User Authenticator #8/INFO UUID of player <username> is <uuid>
21.05 17:10:13 [Connect] User <username>, IP <ip>
21.05 17:10:13 [PebbleHost] <username> ran command Message of the Day
21.05 17:10:13 [Server] Server thread/INFO <username> joined the game
21.05 17:10:13 [Server] Server thread/WARN Failed to handle packet for /<ip>:20517
21.05 17:10:13 [Server] INFO java.lang.NullPointerException: null
21.05 17:10:13 [Server] INFO at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.9) ~[?:?]
21.05 17:10:13 [Server] INFO at java.util.Objects.requireNonNull(Objects.java:221) ~[?:?]
21.05 17:10:13 [Server] INFO at me.basiqueevangelist.worldspecificviewdistance.commands.CommandUtils.getRegistryId(CommandUtils.java:15) ~[worldspecificviewdistance-0.1.0.jar:?]
21.05 17:10:13 [Server] INFO at net.minecraft.server.world.ServerWorld.handler$cel000$onPlayerAdded(ServerWorld:10082) ~[?:?]
21.05 17:10:13 [Server] INFO at net.minecraft.server.world.ServerWorld.addPlayer(ServerWorld) ~[?:?]
21.05 17:10:13 [Server] INFO at net.minecraft.server.world.ServerWorld.onPlayerConnected(ServerWorld:798) ~[?:?]
21.05 17:10:13 [Server] INFO at net.minecraft.server.PlayerManager.onPlayerConnect(PlayerManager:224) ~[?:?]
21.05 17:10:13 [Server] INFO at net.minecraft.server.network.ServerLoginNetworkHandler.acceptPlayer(ServerLoginNetworkHandler:113) ~[?:?]
21.05 17:10:13 [Server] INFO at net.minecraft.server.network.ServerLoginNetworkHandler.redirect$can000$handlePlayerJoin(ServerLoginNetworkHandler:1062) ~[?:?]
21.05 17:10:13 [Server] INFO at net.minecraft.server.network.ServerLoginNetworkHandler.tick(ServerLoginNetworkHandler:65) ~[?:?]
21.05 17:10:13 [Server] INFO at net.minecraft.network.ClientConnection.tick(ClientConnection:228) ~[?:?]
21.05 17:10:13 [Server] INFO at net.minecraft.server.ServerNetworkIo.tick(ServerNetworkIo:173) ~[?:?]
21.05 17:10:13 [Server] INFO at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:882) ~[intermediary-server.jar:?]
21.05 17:10:13 [Server] INFO at net.minecraft.server.dedicated.MinecraftDedicatedServer.tickWorlds(MinecraftDedicatedServer:312) ~[?:?]
21.05 17:10:13 [Server] INFO at net.minecraft.server.MinecraftServer.tick(MinecraftServer:811) ~[intermediary-server.jar:?]
21.05 17:10:13 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:670) ~[intermediary-server.jar:?]
21.05 17:10:13 [Server] INFO at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:257) ~[intermediary-server.jar:?]
21.05 17:10:13 [Server] INFO at java.lang.Thread.run(Thread.java:829) [?:?]
21.05 17:10:13 [Disconnect] User <username> has disconnected, reason: Internal server error
21.05 17:10:13 [Server] Server thread/INFO <username> left the game
```
This is in the Earth Space dimension provided by Astromine. I got a user report that chunks were not loading for them (about 10 minutes after I had changed global viewdistance from 6 to 4), and once I (an OP) teleported to the other user, both of us subsequently got disconnected, and kept getting disconnected until I restarted the server.
After a server restart, all was good, but I don't know how this happened in the first place nor how to reproduce it. This is the second time that this has happened.
It is worth mentioning all of the other mods (most of which are installed on both server and client side, but some server-side only).

<details><summary>Mods list (server)</summary>

```
adorn: Adorn 1.13.0+1.16.5
advanced_runtime_resource_pack: Runtime Resource Pack 0.2.9
adventure-platform-fabric: adventure-platform-fabric 4.0.0-SNAPSHOT
alaskanativecraft: Alaska Native Craft 1.2.0
angerable-patch: Angerable Patch 1.1.0-1.16.4
astromine: Astromine 1.11.5+fabric-1.16.5
astromine-core: Astromine: Core 1.11.5+fabric-1.16.5
astromine-discoveries: Astromine: Discoveries 1.11.5+fabric-1.16.5
astromine-foundations: Astromine: Foundations 1.11.5+fabric-1.16.5
astromine-technologies: Astromine: Technologies 1.11.5+fabric-1.16.5
astromine-transportations: Astromine: Transportations 1.11.5+fabric-1.16.5
autoconfig1u: Auto Config v1 Updated 3.3.1
backpackmod: Backpack Mod 1.16-1.3.1
bitsandchisels: BitsAndChisels 2.2.0
blade: Blade 2.0.0
caelus: Caelus API 0.0.15-1.16.4
cardinal-components: Cardinal Components API 2.8.3
cardinal-components-base: Cardinal Components API (base) 2.8.3
cardinal-components-block: Cardinal Components API (blocks) 2.8.3
cardinal-components-chunk: Cardinal Components API (chunks) 2.8.3
cardinal-components-entity: Cardinal Components API (entities) 2.8.3
cardinal-components-item: Cardinal Components API (items) 2.8.3
cardinal-components-level: Cardinal Components API (world saves) 2.8.3
cardinal-components-scoreboard: Cardinal Components API (scoreboard) 2.8.3
cardinal-components-util: Cardinal Components API (utilities) 2.8.3
cardinal-components-world: Cardinal Components API (worlds) 2.8.3
cauldronconcrete: Cauldron Concrete 1.0.0+1.16.5-fabric
chainmail: Chainmail 0.5.0
chocobacon: Chocobacon 0.1.0
cinderscapes: Cinderscapes 1.3.3
cloth-basic-math: Cloth Basic Math 0.5.1
cloth-client-events-v0: Cloth Client Events v0 1.5.47
cloth-config2: Cloth Config v4 4.11.26
cloth-datagen-api-v1: Cloth Datagen v1 1.4.9
cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.4.9
cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.2.1
club_minnced_discord-webhooks: discord-webhooks 0.5.6
com_fasterxml_jackson_core_jackson-annotations: jackson-annotations 2.10.1
com_fasterxml_jackson_core_jackson-core: jackson-core 2.10.1
com_fasterxml_jackson_core_jackson-databind: jackson-databind 2.10.1
com_neovisionaries_nv-websocket-client: nv-websocket-client 2.14
com_squareup_okhttp3_okhttp: okhttp 3.14.9
com_squareup_okio_okio: okio 1.17.2
com_vdurmont_emoji-java: emoji-java 5.1.1
consistency_plus: Consistency Plus 0.3.0
crimsonmoon: Crimson Moon 2.0.4-1.16.5
croptopia: Croptopia 1.4.0
crowdin-translate: CrowdinTranslate 1.2
customportalapi: Custom Portals 0.0.1-beta29-1.16
dazzle: Dazzle 2 1.0
direbats: Direbats 1.1.1+1.16.5-fabric
dynmap: Dynmap 3.1
earthtojavamobs: Earth2Java 1.7.0+1.16.4
eldritch_mobs: Eldritch Mobs 1.6.9
expandedstorage: ExpandedStorage 5.6.33
extraorigins: Extra Origins 1.16.5-11
fabric: Fabric API 0.34.2+1.16
fabric-api-base: Fabric API Base 0.3.0+c88702897d
fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.0.0+dc716ea17d
fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
fabric-command-api-v1: Fabric Command API (v1) 1.1.1+351679a77d
fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.6+61336ba97d
fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+c88702897d
fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.7+2868a2287d
fabric-language-kotlin: Fabric Language Kotlin 1.6.0+kotlin.1.5.0
fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
fabric-networking-api-v1: Fabric Networking API (v1) 1.0.3+e3c9d0627d
fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.5+c88702897d
fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.6+2868a2287d
fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.7+8183d3957d
fabricloader: Fabric Loader 0.11.3
fabricsit: FabricSit 1.4.0
fallflyinglib: FallFlyingLib 1.1.0
fastbench: FastBench 2.3
fastfurnace: FastFurnace 2.4
fatxporbs: Fat Experience Orbs 0.0.9
fdlink: Fabric <-> Discord Link 0.9.0
fdlink_1_12_2: Fabric <-> Discord Link 0.9.0
fdlink_1_15_2: Fabric <-> Discord Link 0.9.0
fdlink_1_16: Fabric <-> Discord Link 0.9.0
fdlink_1_7_10: Fabric <-> Discord Link 0.9.0
fdlink_1_8_9: Fabric <-> Discord Link 0.9.0
fdlink_api: Fabric <-> Discord Link API 0.1.0
fdlink_common: Fabric <-> Discord Link 0.9.0
fedora: Fedora 1.1.1-fabric-1.16.4
fermion: Fermion 2.1.191
fermion-modkeys: Fermion Modifier Keys 1.10.218
fgf: Food, Glorious Food! 1.0.0
fiber: fiber 0.23.0-2
flamingo_ooo: Flamingo, oh, oh, oh... 1.0.4-MC1.16.3-fabric
flesh2leather: Flesh2Leather 1.0.2
flytre_lib: FlytreLib 0.2.10
fryingpan: Frying Pan! 1.0.2
geckolib3: Geckolib 3.0.34
gentlefawn: GentleFawn 1.1.4-MC1.16.5-fabric
gravestones: Gravestones v1.9
headindex: Head Index 1.0.0
hotm: Heart of the Machine 1.16.3-0.1.7
hydrogen: Hydrogen 0.2
invview: InvView 1.3.0-1.16.4+
jankson: Jankson 3.0.1+j1.2.0
java: OpenJDK 64-Bit Server VM 11
kibe: Kibe 1.6.7-BETA
krypton: Krypton 0.1.2
lazydfu: LazyDFU 0.1.2
libblockattributes_core: LibBlockAttributes (Core) 0.8.7
libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.7
libblockattributes_items: LibBlockAttributes (Items) 0.8.5
libcd: LibCapableData 3.0.3+1.16.3
libgui: LibGui 3.3.5+1.16.5
libstructure: Libstructure 1.3
lithium: Lithium 0.6.4
ltr: LilTaterReloaded 1.1.10+1.16.3
magna: Magna 1.4.3-1.16.2
maybe-data: Maybe data 1.0.0-1.16.2
mealapi: Meal API 0.1+1.16.2
minecraft: Minecraft 1.16.5
moborigins: Mob Origins 1.4.0
mobz: MobZ 2.4.6
nbtcrafting: NBT Crafting 2.0.1+mc1.16.4
net_dv8tion_jda: JDA 4.2.1_255
net_kyori_adventure-api: adventure-api 4.7.0
net_kyori_adventure-key: adventure-key 4.7.0
net_kyori_adventure-platform-api: adventure-platform-api 4.0.0-SNAPSHOT
net_kyori_adventure-text-feature-pagination: adventure-text-feature-pagination 4.0.0-SNAPSHOT
net_kyori_adventure-text-minimessage: adventure-text-minimessage 4.1.0-SNAPSHOT
net_kyori_adventure-text-serializer-gson: adventure-text-serializer-gson 4.7.0
net_kyori_adventure-text-serializer-plain: adventure-text-serializer-plain 4.7.0
net_kyori_examination-api: examination-api 1.1.0
net_kyori_examination-string: examination-string 1.1.0
net_sf_trove4j_trove4j: trove4j 3.0.3
notenoughcrashes: Not Enough Crashes 3.2.0
omega-config: OmegaConfig 1.0.4
org_apache_commons_commons-collections4: commons-collections4 4.1
org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.0
org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.0
org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.0
org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.0
org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.0-RC
org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.0-RC
org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.0
org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.0
org_joml_joml: joml 1.10.0
org_json_json: json 20210307
org_slf4j_slf4j-api: slf4j-api 1.7.25
org_slf4j_slf4j-nop: slf4j-nop 1.7.25
org_yaml_snakeyaml: snakeyaml 1.26
origins: Origins 0.7.1
originsplus: Origins Plus 0.0.2
packet_tweaker: Packet Tweaker 0.1.2
patchouli: Patchouli 1.16.4-50-FABRIC
pehkui: Pehkui 2.1.0+21w18a
piglib: Piglib 1.0.1
placeholder-api: Fabric Placeholder API 0.3.0
player_events: Player Events 2.1.0
player_events_api: Player Events API 2.1.0
playerabilitylib: Pal 1.2.1
polymorph: Polymorph 0.0.10-1.16.5
prideflags: Pride Flags 0.3.1
ratsmischief: Rat's Mischief 1.1.1
reach-entity-attributes: Reach Entity Attributes 1.1.1
reborncore: Reborn Core 4.7.2+build.132
repurposed_structures: Repurposed Structures 1.16.5-1.10.5-fabric
roughlyenoughitems: Roughly Enough Items 5.11.218
roughlyenoughitems-api: REI (API) 5.11.218
roughlyenoughitems-default-plugin: REI (Default Plugin) 5.11.218
roughlyenoughitems-runtime: REI (Runtime) 5.11.218
sandwichable: Sandwichable 1.2-beta5
seedy-behavior: Seedy Behavior 1.0.1
server_translations_api: Server Translations API 1.4.1
sgui: SGui 0.3.1
shapes: Shapes 2.0.0+build.10
slimeorigin: Slimeorigin 3.0.0
stacc: Stacc 1.0.1
starlight: Starlight fabric-1.0.0-RC2-82ae5ca
styledplayerlist: Styled Player List 1.2.1
team_reborn_energy: Energy 0.1.1
techreborn: Tech Reborn 3.8.3+build.231
terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 1.0.4
terraform-config-api-v1: Terraform Config API (v1) 1.0.3
terraform-dirt-api-v1: Terraform Dirt API (v1) 1.1.3
terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 1.0.3
terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.3
terraform-surfaces-api-v1: Terraform Surfaces API (v1) 1.0.3
terraform-tree-api-v1: Terraform Tree API (v1) 1.0.4
terraform-wood-api-v1: Terraform Wood API (v1) 1.0.3
terrestria: Terrestria 2.2.0
the_aether: The Aether 1.16.5-1.0.3
toomanyorigins: TooManyOrigins 0.1.3
trade: Trade 1.1.3
traverse: Traverse 3.3.2
trinkets: Trinkets 2.6.7
untitledduckmod: Untitled Duck Mod 0.2.1
voyager: Voyager 1.0.0
waystones: Waystones 1.1.1.1
worldedit: WorldEdit 7.2.5+57d5ac9
worldspecificviewdistance: World Specific View Distance 0.1.0
wrenchable: Wrenchable 1.0.0+1.16.1
xlpackets: XLPackets 1.1
zoob: Monster Of The Ocean Depths 3.0.0
```

</details>

I understand if this is not actionable, as I can't quite reproduce it.

Thank you :)

**Comment by triphora** [comment]
After testing for a few hours, it looks like it all works
